% script to make colored image of EEG/EMG data for autoscoring grant (and talks)

% load plotting_nice_EEG.mat


figure

% First plot the EEG data (colored for state)
surface('XData', [xplotdownsampled2 xplotdownsampled2],             ... % N.B.  XYZC Data must have at least 2 cols
        'YData', [0.8*EEG_in_window_downsampled 0.8*EEG_in_window_downsampled],             ...
        'ZData', zeros(numel(xplotdownsampled2),2), ...
        'CData', [scores_high_freq_new_downsampled scores_high_freq_new_downsampled],             ...
        'FaceColor', 'none',        ...
        'EdgeColor', 'interp',      ...
        'Marker', 'none');

hold on 
% Now plot the EMG data (colored for state)
surface('XData', [xplotdownsampled2 xplotdownsampled2],             ... % N.B.  XYZC Data must have at least 2 cols
        'YData', [0.3*EMG_in_window_downsampled-0.5 0.3*EMG_in_window_downsampled-0.5],             ...
        'ZData', zeros(numel(xplotdownsampled2),2), ...
        'CData', [scores_high_freq_new_downsampled scores_high_freq_new_downsampled],             ...
        'FaceColor', 'none',        ...
        'EdgeColor', 'interp',      ...
        'Marker', 'none');
hold off

axis off
set(gca,'color','none')
